/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controller.DB4OModel.DB4OModel;
import Controller.Department.Department;
import Controller.Enterprise.Enterprise;
import Controller.HealthNGO;
import Controller.Network.Network;
import Controller.Users.Users;
import gui.stardardLogin.AdministrationAssisatanceJPanel;
import gui.stardardLogin.CommunityEventsParticipantsJPanel;
import gui.stardardLogin.DonarJPanel;
import gui.stardardLogin.LifeLineAgentJPanel;
import gui.stardardLogin.MedicalJPanel;
import gui.stardardLogin.MentalHealthWarriorJPanel;
import gui.stardardLogin.MentalHealthWarriorRepresentativeJPanel;
import gui.stardardLogin.NGOJPanel;
import gui.stardardLogin.NLPTrainerJPanel;
import gui.stardardLogin.PharmacyJPanel;
import gui.stardardLogin.RehabCenterJPanel;
import gui.stardardLogin.SysAdminJPanel;
import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Saamu
 */
public class StartUI extends javax.swing.JFrame {

    /**
     * Creates new form startUI
     */
    
    private HealthNGO system;
    private DB4OModel dB4OUtil = DB4OModel.getInstance();
    public StartUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("withYouNGO-logo.jpg")));
        system = dB4OUtil.retrieveSystem();
//        this.setSize(1480, 1050);
        
        this.stardardLoginjPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logincontainerJPanel = new javax.swing.JPanel();
        sysadminLoginjPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adminUserNameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adminPasswordField = new javax.swing.JPasswordField();
        loginSysadminbtn = new javax.swing.JButton();
        stardardLoginjPanel = new javax.swing.JPanel();
        mHWLoginjBtn = new javax.swing.JButton();
        wPLoginjBtn = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        sysadminLoginjBtn2 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        donarLoginjBtn = new javax.swing.JButton();
        rehabCenterLoginjBtn = new javax.swing.JButton();
        communityEventsPartLoginjBtn = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        logincontainerJPanel.setBackground(new java.awt.Color(0, 102, 102));

        sysadminLoginjPanel.setBackground(new java.awt.Color(0, 102, 102));
        sysadminLoginjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sysadmin Only", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        sysadminLoginjPanel.setMinimumSize(new java.awt.Dimension(230, 0));

        jLabel5.setText("Admin Username");

        jLabel6.setText("Password");

        loginSysadminbtn.setBackground(new java.awt.Color(204, 255, 204));
        loginSysadminbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginSysadminbtn.setText("Login");
        loginSysadminbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        loginSysadminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSysadminbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sysadminLoginjPanelLayout = new javax.swing.GroupLayout(sysadminLoginjPanel);
        sysadminLoginjPanel.setLayout(sysadminLoginjPanelLayout);
        sysadminLoginjPanelLayout.setHorizontalGroup(
            sysadminLoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminLoginjPanelLayout.createSequentialGroup()
                .addGroup(sysadminLoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(adminPasswordField)
            .addComponent(adminUserNameJTextField)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sysadminLoginjPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginSysadminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sysadminLoginjPanelLayout.setVerticalGroup(
            sysadminLoginjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sysadminLoginjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminUserNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginSysadminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stardardLoginjPanel.setBackground(new java.awt.Color(0, 102, 102));
        stardardLoginjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Select Role", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        stardardLoginjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mHWLoginjBtn.setBackground(new java.awt.Color(204, 255, 204));
        mHWLoginjBtn.setText("Mental health Warrior");
        mHWLoginjBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        mHWLoginjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHWLoginjBtnActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(mHWLoginjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 31, 230, 34));

        wPLoginjBtn.setBackground(new java.awt.Color(204, 255, 204));
        wPLoginjBtn.setText("Warrior Representative");
        wPLoginjBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        wPLoginjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wPLoginjBtnActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(wPLoginjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 71, 230, 34));

        jButton.setBackground(new java.awt.Color(204, 255, 204));
        jButton.setText("Lifeline Agent");
        jButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 241, 230, 34));

        jButton29.setBackground(new java.awt.Color(204, 255, 204));
        jButton29.setText("Administration Assistance");
        jButton29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 281, 230, 34));

        sysadminLoginjBtn2.setBackground(new java.awt.Color(204, 255, 204));
        sysadminLoginjBtn2.setText("Sysadmin Admin");
        sysadminLoginjBtn2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        sysadminLoginjBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysadminLoginjBtn2ActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(sysadminLoginjBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 481, 230, 34));

        jButton30.setBackground(new java.awt.Color(204, 255, 204));
        jButton30.setText("NLP Trainer");
        jButton30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 321, 230, 34));

        donarLoginjBtn.setBackground(new java.awt.Color(204, 255, 204));
        donarLoginjBtn.setText("Donor");
        donarLoginjBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        donarLoginjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donarLoginjBtnActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(donarLoginjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 111, 230, 34));

        rehabCenterLoginjBtn.setBackground(new java.awt.Color(204, 255, 204));
        rehabCenterLoginjBtn.setText("Rehab Doctor");
        rehabCenterLoginjBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        rehabCenterLoginjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rehabCenterLoginjBtnActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(rehabCenterLoginjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 151, 230, 34));

        communityEventsPartLoginjBtn.setBackground(new java.awt.Color(204, 255, 204));
        communityEventsPartLoginjBtn.setText("Community Events Participants");
        communityEventsPartLoginjBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        communityEventsPartLoginjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityEventsPartLoginjBtnActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(communityEventsPartLoginjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 196, 230, 34));

        jButton22.setBackground(new java.awt.Color(204, 255, 204));
        jButton22.setText("NGOs");
        jButton22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 361, 230, 34));

        jButton23.setBackground(new java.awt.Color(204, 255, 204));
        jButton23.setText("Medicals");
        jButton23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 401, 230, 34));

        jButton24.setBackground(new java.awt.Color(204, 255, 204));
        jButton24.setText("Pharmacy");
        jButton24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 102, 102)));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        stardardLoginjPanel.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 441, 230, 34));

        javax.swing.GroupLayout logincontainerJPanelLayout = new javax.swing.GroupLayout(logincontainerJPanel);
        logincontainerJPanel.setLayout(logincontainerJPanelLayout);
        logincontainerJPanelLayout.setHorizontalGroup(
            logincontainerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stardardLoginjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
            .addComponent(sysadminLoginjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logincontainerJPanelLayout.setVerticalGroup(
            logincontainerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logincontainerJPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(sysadminLoginjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stardardLoginjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        container.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to WITH You NGO");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(852, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(795, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );

        container.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(logincontainerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(logincontainerJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginSysadminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSysadminbtnActionPerformed
        // Get Admin user name
        String username = adminUserNameJTextField.getText();
        // Get Password
        char[] passwordstr = adminPasswordField.getPassword();
        String password = String.valueOf(passwordstr);

        //Step1: Check in the system user account directory if you have the user
        Users userAccount=system.getUsersDirectory().authenticateUser(username, password);
//        System.out.println(system.getUsersDirectory().getUsersList());
        Enterprise inEnterprise=null;
        Department inDepartment=null;

        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                //Step 2.a: check against each enterprise
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
//                    System.out.println(enterprise.getUsersDirectory().getUsersList());
                    userAccount=enterprise.getUsersDirectory().authenticateUser(username, password);
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Department organization:enterprise.getDepartmentDirectory().getDepartmentList()){
//                            System.out.println(organization.getUsersDirectory().getUsersList());
                            userAccount=organization.getUsersDirectory().authenticateUser(username, password);
                            if(userAccount!=null){
                                inEnterprise=enterprise;
                                inDepartment=organization;
                                break;
                            }
                        }

                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inDepartment!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }

        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Account Not Found or Wrong Password");
            return;
        }
        else{
            boolean isSysAdmin=system.getUsersDirectory().checkIfUsernameIsSysadmin(userAccount.getRole().toString());
            if(isSysAdmin){
                this.stardardLoginjPanel.setVisible(true);
                this.sysadminLoginjPanel.setVisible(false);
                CardLayout layout=(CardLayout)container.getLayout();
                container.add("workArea",userAccount.getRole().createWorkArea(logincontainerJPanel,container, userAccount, inDepartment, inEnterprise, system));
//                                container.add(this.container);
                layout.next(container);

//                                this.networksystemName.setText("Please Select User to Login");
            }
            else{
                JOptionPane.showMessageDialog(null, "Please Use SysAdmin Account");
                return;
            }
        }
        adminUserNameJTextField.setText("");
        adminPasswordField.setText("");
    }//GEN-LAST:event_loginSysadminbtnActionPerformed

    private void mHWLoginjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHWLoginjBtnActionPerformed
        MentalHealthWarriorJPanel mentalHealthWarriorJPanel=new MentalHealthWarriorJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("mentalHealthWarriorJPanel",mentalHealthWarriorJPanel);
        layout.next(container);
    }//GEN-LAST:event_mHWLoginjBtnActionPerformed

    private void wPLoginjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wPLoginjBtnActionPerformed
        MentalHealthWarriorRepresentativeJPanel mentalHealthWarriorRepresentativeJPanel=new MentalHealthWarriorRepresentativeJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("mentalHealthWarriorRepresentativeJPanel",mentalHealthWarriorRepresentativeJPanel);
        layout.next(container);
    }//GEN-LAST:event_wPLoginjBtnActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        LifeLineAgentJPanel lifelineagentJPanel=new LifeLineAgentJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("lifelineagentJPanel",lifelineagentJPanel);
        layout.next(container);
    }//GEN-LAST:event_jButtonActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        AdministrationAssisatanceJPanel adminAssistanceJPanel=new AdministrationAssisatanceJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("adminAssistanceJPanel",adminAssistanceJPanel);
        layout.next(container);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void sysadminLoginjBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysadminLoginjBtn2ActionPerformed
        SysAdminJPanel sysadminJPanel=new SysAdminJPanel(sysadminLoginjPanel,stardardLoginjPanel,logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("sysadminJPanel",sysadminJPanel);
        layout.next(container);
    }//GEN-LAST:event_sysadminLoginjBtn2ActionPerformed

    private void donarLoginjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donarLoginjBtnActionPerformed
        DonarJPanel communityEventParticipantsJPanel=new DonarJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("communityEventParticipantsJPanel",communityEventParticipantsJPanel);
        layout.next(container);
    }//GEN-LAST:event_donarLoginjBtnActionPerformed

    private void rehabCenterLoginjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehabCenterLoginjBtnActionPerformed
        RehabCenterJPanel rehabCenterJPanel=new RehabCenterJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("rehabCenterJPanel",rehabCenterJPanel);
        layout.next(container);
    }//GEN-LAST:event_rehabCenterLoginjBtnActionPerformed

    private void communityEventsPartLoginjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityEventsPartLoginjBtnActionPerformed
        CommunityEventsParticipantsJPanel CommunityEventsParticipantsJPanel=new CommunityEventsParticipantsJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("CommunityEventsParticipantsJPanel",CommunityEventsParticipantsJPanel);
        layout.next(container);
    }//GEN-LAST:event_communityEventsPartLoginjBtnActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        NGOJPanel ngoJPanel=new NGOJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("ngoJPanel",ngoJPanel);
        layout.next(container);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        MedicalJPanel medicalJPanel=new MedicalJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("medicalJPanel",medicalJPanel);
        layout.next(container);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        PharmacyJPanel pharmacyJPanel=new PharmacyJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("pharmacyJPanel",pharmacyJPanel);
        layout.next(container);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        NLPTrainerJPanel nlpTrainerJPanel=new NLPTrainerJPanel(logincontainerJPanel,container,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("nlpTrainerJPanel",nlpTrainerJPanel);
        layout.next(container);
    }//GEN-LAST:event_jButton30ActionPerformed
    
    public void closeLoginPanel(){
        this.logincontainerJPanel.setVisible(false);
        this.container.removeAll();
//        this.container.add(welcomelgnjPanel);
//        this.networksystemName.setText("Your have been Logged Out.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JTextField adminUserNameJTextField;
    private javax.swing.JButton communityEventsPartLoginjBtn;
    private javax.swing.JPanel container;
    private javax.swing.JButton donarLoginjBtn;
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton loginSysadminbtn;
    public javax.swing.JPanel logincontainerJPanel;
    private javax.swing.JButton mHWLoginjBtn;
    private javax.swing.JButton rehabCenterLoginjBtn;
    public javax.swing.JPanel stardardLoginjPanel;
    private javax.swing.JButton sysadminLoginjBtn2;
    public javax.swing.JPanel sysadminLoginjPanel;
    private javax.swing.JButton wPLoginjBtn;
    // End of variables declaration//GEN-END:variables
}
