/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.MentalHealthRepRole;

import Controller.DB4OModel.DB4OModel;
import Controller.Department.Department;
import Controller.Department.SupportDepartment;
import Controller.Enterprise.Enterprise;
import Controller.HealthNGO;
import Controller.Network.Network;
import Controller.Users.Users;
import Controller.WorkQueue.PatientRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class MentalHealthRepWorkerAddictionjPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerSuicideIdeationjPanel
     */
    private HealthNGO system;
    private Department org,supportOrg;
    private JPanel container,logincontainerJPanel;
    private Users user;
    private DB4OModel dB4OModel = DB4OModel.getInstance();
    public MentalHealthRepWorkerAddictionjPanel(JPanel logincontainerJPanel,JPanel container, Users user, HealthNGO system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.user=user;
        this.loggedmhwjLabel.setText("Hi, "+user.toFullname()+"("+user.getRole()+")");
        String networkname="";
        for(Network network:system.getNetworkList()){
            networkname=network.getName();
        }
        this.networknamejLabel.setText(networkname);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loggedmhwjLabel = new javax.swing.JLabel();
        mhwLogoutjButton = new javax.swing.JButton();
        networknamejLabel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        alcoholaddictjButton = new javax.swing.JButton();
        drugaddictjButton = new javax.swing.JButton();
        pornographicaddictjButton = new javax.swing.JButton();
        foodaddictjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loggedmhwjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loggedmhwjLabel.setText("Logged Username");
        loggedmhwjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mhwLogoutjButton.setBackground(new java.awt.Color(255, 255, 204));
        mhwLogoutjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mhwLogoutjButton.setText("Logout");
        mhwLogoutjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        mhwLogoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhwLogoutjButtonActionPerformed(evt);
            }
        });

        networknamejLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        networknamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        networknamejLabel.setText("Logged Network");
        networknamejLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setText("<<Back");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(networknamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(networknamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Choose Your Addiction", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        alcoholaddictjButton.setBackground(new java.awt.Color(204, 255, 204));
        alcoholaddictjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alcoholaddictjButton.setText("1. Alcohol Addiction");
        alcoholaddictjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        alcoholaddictjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcoholaddictjButtonActionPerformed(evt);
            }
        });

        drugaddictjButton.setBackground(new java.awt.Color(204, 255, 204));
        drugaddictjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugaddictjButton.setText("2. Drug Addiction");
        drugaddictjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        drugaddictjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugaddictjButtonActionPerformed(evt);
            }
        });

        pornographicaddictjButton.setBackground(new java.awt.Color(204, 255, 204));
        pornographicaddictjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pornographicaddictjButton.setText("3. Pornographic Addiction");
        pornographicaddictjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        pornographicaddictjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pornographicaddictjButtonActionPerformed(evt);
            }
        });

        foodaddictjButton.setBackground(new java.awt.Color(204, 255, 204));
        foodaddictjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foodaddictjButton.setText("4. Food Addiction");
        foodaddictjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        foodaddictjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodaddictjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foodaddictjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pornographicaddictjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(alcoholaddictjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drugaddictjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alcoholaddictjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drugaddictjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pornographicaddictjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(foodaddictjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mhwLogoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhwLogoutjButtonActionPerformed
        JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;
    
        logincontainerJPanel.setVisible(true);
        container.removeAll();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Logged Out. Please Login to Continue");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        container.add(jPanel6);
    }//GEN-LAST:event_mhwLogoutjButtonActionPerformed

    private void alcoholaddictjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcoholaddictjButtonActionPerformed
        int confirm=JOptionPane.showConfirmDialog(null, "Submit Alcohol Addiction?", "Alcohol Addiction", JOptionPane.YES_NO_OPTION);
        if(confirm==0){
        String message = "Alcohol Addiction Issues";
        PatientRequest request = new PatientRequest();
        request.setMessage(message);
        request.setSender(user);
        request.setStatus("Addiction Sent");
        for(Network network:system.getNetworkList()){
                for(Enterprise enterprises:network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Department depart : enterprises.getDepartmentDirectory().getDepartmentList()){
                        if (depart instanceof SupportDepartment){
                            supportOrg = depart;
                            break;
                        }
                    }

                }
            }

            if(supportOrg==null){
                JOptionPane.showMessageDialog(null, "Addiction Issue not Sent");
                return;
            }
        supportOrg.getWorkQueue().getWorkRequestList().add(request);
        user.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Issue Submitted.\nA Please check your Phamacy option for responses.");
        dB4OModel.storeSystem(system);
        }
    }//GEN-LAST:event_alcoholaddictjButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MentalHealthRepWorkerHomejPanel dwjp = (MentalHealthRepWorkerHomejPanel) component;
        dwjp.previousRequets();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void drugaddictjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugaddictjButtonActionPerformed
        int confirm=JOptionPane.showConfirmDialog(null, "Submit Drug Addiction?", "Drug Addiction", JOptionPane.YES_NO_OPTION);
        if(confirm==0){
        String message = "Drug Addiction Issues";
        PatientRequest request = new PatientRequest();
        request.setMessage(message);
        request.setSender(user);
        request.setStatus("Addiction Sent");
        for(Network network:system.getNetworkList()){
                for(Enterprise enterprises:network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Department depart : enterprises.getDepartmentDirectory().getDepartmentList()){
                        if (depart instanceof SupportDepartment){
                            supportOrg = depart;
                            break;
                        }
                    }

                }
            }

            if(supportOrg==null){
                JOptionPane.showMessageDialog(null, "Addiction Issue not Sent");
                return;
            }
        supportOrg.getWorkQueue().getWorkRequestList().add(request);
        user.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Issue Submitted.\nA Please check your Phamacy option for responses.");
        dB4OModel.storeSystem(system);
        }
    }//GEN-LAST:event_drugaddictjButtonActionPerformed

    private void pornographicaddictjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pornographicaddictjButtonActionPerformed
        int confirm=JOptionPane.showConfirmDialog(null, "Submit Pornographic Addiction?", "Pornographic Addiction", JOptionPane.YES_NO_OPTION);
        if(confirm==0){
        String message = "Pornographic Addiction Issues";
        PatientRequest request = new PatientRequest();
        request.setMessage(message);
        request.setSender(user);
        request.setStatus("Addiction Sent");
        for(Network network:system.getNetworkList()){
                for(Enterprise enterprises:network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Department depart : enterprises.getDepartmentDirectory().getDepartmentList()){
                        if (depart instanceof SupportDepartment){
                            supportOrg = depart;
                            break;
                        }
                    }

                }
            }

            if(supportOrg==null){
                JOptionPane.showMessageDialog(null, "Addiction Issue not Sent");
                return;
            }
        supportOrg.getWorkQueue().getWorkRequestList().add(request);
        user.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Issue Submitted.\nA Please check your Phamacy option for responses.");
        dB4OModel.storeSystem(system);
        }
    }//GEN-LAST:event_pornographicaddictjButtonActionPerformed

    private void foodaddictjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodaddictjButtonActionPerformed
        int confirm=JOptionPane.showConfirmDialog(null, "Submit Food Addiction?", "Food Addiction", JOptionPane.YES_NO_OPTION);
        if(confirm==0){
        String message = "Food Addiction Issues";
        PatientRequest request = new PatientRequest();
        request.setMessage(message);
        request.setSender(user);
        request.setStatus("Addiction Sent");
        for(Network network:system.getNetworkList()){
                for(Enterprise enterprises:network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Department depart : enterprises.getDepartmentDirectory().getDepartmentList()){
                        if (depart instanceof SupportDepartment){
                            supportOrg = depart;
                            break;
                        }
                    }

                }
            }

            if(supportOrg==null){
                JOptionPane.showMessageDialog(null, "Addiction Issue not Sent");
                return;
            }
        supportOrg.getWorkQueue().getWorkRequestList().add(request);
        user.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Issue Submitted.\nA Please check your Phamacy option for responses.");
        dB4OModel.storeSystem(system);
        }
    }//GEN-LAST:event_foodaddictjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alcoholaddictjButton;
    private javax.swing.JButton drugaddictjButton;
    private javax.swing.JButton foodaddictjButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loggedmhwjLabel;
    private javax.swing.JButton mhwLogoutjButton;
    private javax.swing.JLabel networknamejLabel;
    private javax.swing.JButton pornographicaddictjButton;
    // End of variables declaration//GEN-END:variables
}
