/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.AdministrationAssistance;

import Controller.DB4OModel.DB4OModel;
import Controller.Department.Department;
import Controller.Department.DepartmentDirectory;
import Controller.Employee.Employee;
import Controller.Enterprise.Enterprise;
import Controller.HealthNGO;
import Controller.Network.Network;
import Controller.Role.Role;
import Controller.Users.Users;
import java.awt.CardLayout;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class AdministrationAssistanceWorkerDepartmentUserConfigjPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerjPanel
     */
    private HealthNGO system;
    private Enterprise enterprise;
    private DepartmentDirectory directory;
    private JPanel container,logincontainerJPanel;
    private Users user;
    private DB4OModel dB4OModel = DB4OModel.getInstance();
    private DefaultComboBoxModel days=new DefaultComboBoxModel();
    public AdministrationAssistanceWorkerDepartmentUserConfigjPanel(JPanel logincontainerJPanel,JPanel container,Enterprise enterprise,DepartmentDirectory directory, Users user, HealthNGO system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.enterprise=enterprise;
        this.directory=directory;
        this.user=user;
        this.loggedmhwjLabel.setText("Hi, "+user.getEmployee()+"("+user.getRole()+")");
        String networkname="";
        for(Network network:system.getNetworkList()){
            networkname=network.getName();
        }
        this.networknamejLabel.setText(networkname);
        enterprisenamejLabel.setText(enterprise.getName());
        newEnterprisejButton.setVisible(false);
        updateEnterprisejButton.setVisible(false);
        deleteEnterprisejButton.setVisible(false);
        saveEnterprisejButton.setVisible(true);
        popDepartmentComboBox();
        displayDepartmentUsers();
        
        yearjComboBox.removeAll();
        LocalDate nowDate=LocalDate.now();
        int year=nowDate.getYear();
        int startYear=1940;
        
        for(int i=year;i>=startYear;i--){
            yearjComboBox.addItem(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loggedmhwjLabel = new javax.swing.JLabel();
        mhwLogoutjButton = new javax.swing.JButton();
        networknamejLabel = new javax.swing.JLabel();
        enterprisenamejLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisessjTable = new javax.swing.JTable();
        newUserjPanel = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        firstnamejTextField = new javax.swing.JTextField();
        lastnamejTextField = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        addressjTextField = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        statejTextField = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        zipcodejTextField = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        phonejTextField = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        emailIdjTextField = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        ssnnumberjTextField = new javax.swing.JTextField();
        sexjComboBox = new javax.swing.JComboBox<>();
        yearjComboBox = new javax.swing.JComboBox<>();
        monthjComboBox = new javax.swing.JComboBox<>();
        dayjComboBox = new javax.swing.JComboBox<>();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        passwordjPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        departmentjComboBox = new javax.swing.JComboBox();
        employeeComboBox = new javax.swing.JComboBox();
        rolejComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        updateEnterprisejButton = new javax.swing.JButton();
        deleteEnterprisejButton = new javax.swing.JButton();
        newEnterprisejButton = new javax.swing.JButton();
        saveEnterprisejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ngoidjTextField = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loggedmhwjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loggedmhwjLabel.setText("Logged Username");
        loggedmhwjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mhwLogoutjButton.setBackground(new java.awt.Color(255, 255, 204));
        mhwLogoutjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mhwLogoutjButton.setText("Logout");
        mhwLogoutjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        mhwLogoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhwLogoutjButtonActionPerformed(evt);
            }
        });

        networknamejLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        networknamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        networknamejLabel.setText("Logged Network");
        networknamejLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        enterprisenamejLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enterprisenamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterprisenamejLabel.setText("Enterprise");
        enterprisenamejLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("<< Back");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networknamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterprisenamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(enterprisenamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(networknamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Users", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        enterprisessjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Role", "Employee"
            }
        ));
        enterprisessjTable.setGridColor(java.awt.SystemColor.window);
        enterprisessjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterprisessjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterprisessjTable);

        newUserjPanel.setBackground(new java.awt.Color(0, 153, 153));
        newUserjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New NGO User", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        newUserjPanel.setAutoscrolls(true);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel41.setText("First Name");

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel43.setText("Date of Birth");

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel44.setText("Sex");

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel45.setText("Address");

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel46.setText("City");

        jLabel47.setText("State");

        jLabel48.setText("Zip Code");

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel49.setText("Phone");

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel50.setText("Email");

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel51.setText("SSN Number");

        sexjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Both", "Other" }));

        yearjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearjComboBoxActionPerformed(evt);
            }
        });

        monthjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthjComboBoxActionPerformed(evt);
            }
        });

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel57.setText("Username");

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel58.setText("Password");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Department");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Employee Name");

        departmentjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentjComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Role");

        updateEnterprisejButton.setBackground(new java.awt.Color(204, 255, 204));
        updateEnterprisejButton.setText("Update");
        updateEnterprisejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        updateEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEnterprisejButtonActionPerformed(evt);
            }
        });

        deleteEnterprisejButton.setBackground(new java.awt.Color(204, 255, 204));
        deleteEnterprisejButton.setText("Delete");
        deleteEnterprisejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        deleteEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnterprisejButtonActionPerformed(evt);
            }
        });

        newEnterprisejButton.setBackground(new java.awt.Color(204, 255, 204));
        newEnterprisejButton.setText("New");
        newEnterprisejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        newEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEnterprisejButtonActionPerformed(evt);
            }
        });

        saveEnterprisejButton.setBackground(new java.awt.Color(204, 255, 204));
        saveEnterprisejButton.setText("Save");
        saveEnterprisejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        saveEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEnterprisejButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("NGO ID");

        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel59.setText("Last");

        javax.swing.GroupLayout newUserjPanelLayout = new javax.swing.GroupLayout(newUserjPanel);
        newUserjPanel.setLayout(newUserjPanelLayout);
        newUserjPanelLayout.setHorizontalGroup(
            newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserjPanelLayout.createSequentialGroup()
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(sexjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(zipcodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(phonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(emailIdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(ssnnumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngoidjTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(passwordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rolejComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 348, Short.MAX_VALUE)
                            .addComponent(employeeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(firstnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastnamejTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newUserjPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(updateEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        newUserjPanelLayout.setVerticalGroup(
            newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserjPanelLayout.createSequentialGroup()
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstnamejTextField)
                    .addComponent(lastnamejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserjPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ssnnumberjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserjPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngoidjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newUserjPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(newUserjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(deleteEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newUserjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newUserjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mhwLogoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhwLogoutjButtonActionPerformed
        JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;
    
        logincontainerJPanel.setVisible(true);
        container.removeAll();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Logged Out. Please Login to Continue");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        container.add(jPanel6);
    }//GEN-LAST:event_mhwLogoutjButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void enterprisessjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterprisessjTableMouseClicked
        int selectedRow = enterprisessjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No User Selected");
            this.usernamejTextField.setText("");
            passwordjPasswordField.setText("");
            this.firstnamejTextField.setText("");
            sexjComboBox.setSelectedIndex(0);
            this.emailIdjTextField.setText("");
            this.phonejTextField.setText("");
            this.addressjTextField.setText("");
            cityjTextField.setText("");
            this.zipcodejTextField.setText("");
            this.statejTextField.setText("");
            this.ssnnumberjTextField.setText("");
            this.ngoidjTextField.setText("");
            this.rolejComboBox.setSelectedIndex(0);
            this.departmentjComboBox.setSelectedIndex(0);
            this.employeeComboBox.setSelectedIndex(0);
            this.newEnterprisejButton.setVisible(false);
            deleteEnterprisejButton.setVisible(false);
            updateEnterprisejButton.setVisible(false);
            saveEnterprisejButton.setVisible(true);
            return;
        }
        
        Users selUser = (Users)enterprisessjTable.getValueAt(selectedRow, 0);
        this.usernamejTextField.setText(selUser.getUsername());
        passwordjPasswordField.setText(selUser.getPassword());
        
        this.firstnamejTextField.setText(selUser.getFirstname());
        sexjComboBox.setSelectedItem(selUser.getSex());
        this.emailIdjTextField.setText(selUser.getMailId());
        this.phonejTextField.setText(String.valueOf(selUser.getPhone()));
        this.addressjTextField.setText(selUser.getAddress());
        cityjTextField.setText(selUser.getCity());
        this.zipcodejTextField.setText(String.valueOf(selUser.getZipcode()));
        this.statejTextField.setText(selUser.getState());
        this.ssnnumberjTextField.setText(String.valueOf(selUser.getSsnno()));
        this.ngoidjTextField.setText(selUser.getNgoid());
        
        this.rolejComboBox.setSelectedItem(selUser.getRole());
        this.employeeComboBox.setSelectedItem(selUser.getEmployee());
        departmentjComboBox.setSelectedIndex(0);
        newEnterprisejButton.setVisible(true);
        updateEnterprisejButton.setVisible(true);
        deleteEnterprisejButton.setVisible(true);
        saveEnterprisejButton.setVisible(false);
    }//GEN-LAST:event_enterprisessjTableMouseClicked

    private void saveEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEnterprisejButtonActionPerformed
        //Submit Details
        String yy=String.valueOf(this.yearjComboBox.getSelectedItem());
        String mm=String.valueOf(this.monthjComboBox.getSelectedItem());
        String dd=String.valueOf(this.dayjComboBox.getSelectedItem());
        String dob=yy+"-"+mm+"-"+dd;

        String username = this.usernamejTextField.getText().trim();
        char[] passwordRaw = this.passwordjPasswordField.getPassword();
        String password = String.valueOf(passwordRaw);
        String firstname = firstnamejTextField.getText().trim();
        String lastname = lastnamejTextField.getText().trim();
        String sex = sexjComboBox.getSelectedItem().toString().trim();
        String mailid = this.emailIdjTextField.getText().trim();
        String phone = this.phonejTextField.getText().trim();
        String address = this.addressjTextField.getText().trim();
        String city = this.cityjTextField.getText().trim();
        String state = this.statejTextField.getText().trim();
        String zipcode = this.zipcodejTextField.getText().trim();
        String ssnno = this.ssnnumberjTextField.getText().trim();
        String ngoids = this.ngoidjTextField.getText().trim();
        int zip;
        Long contactno,ngoid,ssno;
        Department department = (Department) departmentjComboBox.getSelectedItem();
        Role role = (Role) rolejComboBox.getSelectedItem();
        Employee employee = (Employee)employeeComboBox.getSelectedItem();
       
        if(username.isEmpty() || password.isEmpty() || firstname.isEmpty() || lastname.isEmpty() || sex.isEmpty()
            || dob.isEmpty() || mailid.isEmpty() || phone.isEmpty()|| ngoids.isEmpty() 
            || address.isEmpty() || city.isEmpty() || state.isEmpty() || zipcode.isEmpty() || ssnno.isEmpty()
            || employee==null || role==null || department==null){
            JOptionPane.showMessageDialog(this, "Some Data in Fields is Missing", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        try{
            zip=Integer.parseInt(zipcode);
            ssno=Long.valueOf(ssnno);
            contactno=Long.valueOf(phone);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Phone, Emergency Phone,SSN Number and Zip Code Must be a Positive Number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!checkMail(mailid)){
            JOptionPane.showMessageDialog(this, "Check Your Email ID.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (phone.length()<10 || phone.length()>10 ) {
            JOptionPane.showMessageDialog(this, "Phone Number Should be 10 digits.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (zipcode.length()!=5 ) {
            JOptionPane.showMessageDialog(this, "Zip Code Should be 5 digits.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(username.length()<=4) {
            JOptionPane.showMessageDialog(this, "Username should be Five and More Length", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(username.length()>120) {
            JOptionPane.showMessageDialog(this, "Username should be less than 120 length", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(password.length()<=7) {
            JOptionPane.showMessageDialog(this, "Your Password length should be more than 8 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(password.length()>120) {
            JOptionPane.showMessageDialog(this, "Your Password length should be less than 120 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean unique=system.checkIfUserIsUnique(username);
        Enterprise inEnterprise=null;
        Department inDepartment=null;
        Network inNetwork=null;
        //checking if username is taken
        if(unique){
            //Step 1: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                inNetwork=network;
                //Step 2.a: check against each enterprise

                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    unique=enterprise.getUsersDirectory().checkIfUsernameIsUnique(username);
                    if(unique){
                        //Step 3:check against each department for each enterprise
                        for(Department department1:enterprise.getDepartmentDirectory().getDepartmentList()){
                            unique=department1.getUsersDirectory().checkIfUsernameIsUnique(username);
                            if(!unique){
                                inEnterprise=enterprise;
                                inDepartment=department1;
                                break;
                            }
                        }

                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inDepartment!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }

        if(!unique){
            JOptionPane.showMessageDialog(this, "Username Already Taken", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String message=null;
        message="Dear, \n"+firstname+" "+lastname+"\n"+
                "Your are now Registered with us.\n" +
                "Thank you for being WITH you NGO.";
        if(message==null || inNetwork==null){
            JOptionPane.showMessageDialog(null, "The Network is Not Probally Configured.");
            return ;
        }
        if(system.getUsersDirectory().sendFirstLoginNotification(mailid,message,inNetwork).equalsIgnoreCase("Fail")){
            JOptionPane.showMessageDialog(null, "Notification Email Could not sent. Try Again.");
            return ;
        }
        Users newuser=department.getUsersDirectory().createUserAccount(username, password, employee, role, firstname, lastname, dob, sex, address, city, state, zip, contactno, mailid, ssno, null, null, ngoids, null);
        if(newuser.toString()!=null)
        {
            JOptionPane.showMessageDialog(null, newuser.toFullname()+" Added Successfully.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Couuld not Add User.");
            return;
        }
        dB4OModel.storeSystem(system);
        displayDepartmentUsers();
    }                                          

    private void delUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
    }//GEN-LAST:event_saveEnterprisejButtonActionPerformed

    private void updateEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEnterprisejButtonActionPerformed
        int selectedRow = enterprisessjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select User or Add.");
            this.usernamejTextField.setText("");
            passwordjPasswordField.setText("");
            this.firstnamejTextField.setText("");
            sexjComboBox.setSelectedIndex(0);
            this.emailIdjTextField.setText("");
            this.phonejTextField.setText("");
            this.addressjTextField.setText("");
            cityjTextField.setText("");
            this.zipcodejTextField.setText("");
            this.statejTextField.setText("");
            this.ssnnumberjTextField.setText("");
            this.ngoidjTextField.setText("");
            this.rolejComboBox.setSelectedIndex(0);
            this.departmentjComboBox.setSelectedIndex(0);
            this.employeeComboBox.setSelectedIndex(0);
            this.newEnterprisejButton.setVisible(false);
            deleteEnterprisejButton.setVisible(false);
            updateEnterprisejButton.setVisible(false);
            saveEnterprisejButton.setVisible(true);
            return;
        }

        //Update Details
        String username = this.usernamejTextField.getText().trim();
        char[] passwordRaw = this.passwordjPasswordField.getPassword();
        String password = String.valueOf(passwordRaw);
        String firstname = firstnamejTextField.getText().trim();
        String lastname = lastnamejTextField.getText().trim();
        String phone = this.phonejTextField.getText().trim();
        String address = this.addressjTextField.getText().trim();
        String city = this.cityjTextField.getText().trim();
        String state = this.statejTextField.getText().trim();
        String zipcode = this.zipcodejTextField.getText().trim();
        int zip;
        Long contactno;
        Department department = (Department) departmentjComboBox.getSelectedItem();
        Role role = (Role) rolejComboBox.getSelectedItem();
        Employee employee = (Employee)employeeComboBox.getSelectedItem();
       
        if(username.isEmpty() || password.isEmpty() || firstname.isEmpty() || lastname.isEmpty() || phone.isEmpty()||  address.isEmpty() || city.isEmpty() || state.isEmpty() || zipcode.isEmpty()
            || employee==null || role==null || department==null){
            JOptionPane.showMessageDialog(this, "Some Data in Fields is Missing", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        try{
            zip=Integer.parseInt(zipcode);
            contactno=Long.valueOf(phone);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Phone, Emergency Phone,SSN Number and Zip Code Must be a Positive Number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (phone.length()<10 || phone.length()>10 ) {
            JOptionPane.showMessageDialog(this, "Phone Number Should be 10 digits.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (zipcode.length()!=5 ) {
            JOptionPane.showMessageDialog(this, "Zip Code Should be 5 digits.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(username.length()<=4) {
            JOptionPane.showMessageDialog(this, "Username should be Five and More Length", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(username.length()>120) {
            JOptionPane.showMessageDialog(this, "Username should be less than 120 length", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(password.length()<=7) {
            JOptionPane.showMessageDialog(this, "Your Password length should be more than 8 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(password.length()>120) {
            JOptionPane.showMessageDialog(this, "Your Password length should be less than 120 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Users selUser = (Users)enterprisessjTable.getValueAt(selectedRow, 0);
        selUser.setPassword(password);
        selUser.setRole(role);
        selUser.setEmployee(employee);
        selUser.setFirstname(firstname);
        selUser.setLastname(lastname);
        selUser.setCity(city);
        selUser.setPhone(contactno);
        selUser.setAddress(address);
        selUser.setZipcode(zip);
        dB4OModel.storeSystem(system);
        displayDepartmentUsers();
    }//GEN-LAST:event_updateEnterprisejButtonActionPerformed

    private void deleteEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnterprisejButtonActionPerformed
        int selectedRow = enterprisessjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select User or Add.");
            this.usernamejTextField.setText("");
            passwordjPasswordField.setText("");
            this.firstnamejTextField.setText("");
            sexjComboBox.setSelectedIndex(0);
            this.emailIdjTextField.setText("");
            this.phonejTextField.setText("");
            this.addressjTextField.setText("");
            cityjTextField.setText("");
            this.zipcodejTextField.setText("");
            this.statejTextField.setText("");
            this.ssnnumberjTextField.setText("");
            this.ngoidjTextField.setText("");
            this.rolejComboBox.setSelectedIndex(0);
            this.departmentjComboBox.setSelectedIndex(0);
            this.employeeComboBox.setSelectedIndex(0);
            this.newEnterprisejButton.setVisible(false);
            deleteEnterprisejButton.setVisible(false);
            updateEnterprisejButton.setVisible(false);
            saveEnterprisejButton.setVisible(true);
            return;
        }
        Department department = (Department) departmentjComboBox.getSelectedItem();
        Users selUser = (Users)enterprisessjTable.getValueAt(selectedRow, 0);
        department.getUsersDirectory().getUsersList().remove(selUser);
        dB4OModel.storeSystem(system);
        displayDepartmentUsers();
    }//GEN-LAST:event_deleteEnterprisejButtonActionPerformed

    private void newEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEnterprisejButtonActionPerformed
        this.usernamejTextField.setText("");
        passwordjPasswordField.setText("");
        this.firstnamejTextField.setText("");
        sexjComboBox.setSelectedIndex(0);
        this.emailIdjTextField.setText("");
        this.phonejTextField.setText("");
        this.addressjTextField.setText("");
        cityjTextField.setText("");
        this.zipcodejTextField.setText("");
        this.statejTextField.setText("");
        this.ssnnumberjTextField.setText("");
        this.ngoidjTextField.setText("");
        this.rolejComboBox.setSelectedIndex(0);
        this.departmentjComboBox.setSelectedIndex(0);
        this.employeeComboBox.setSelectedIndex(0);
        this.newEnterprisejButton.setVisible(false);
        deleteEnterprisejButton.setVisible(false);
        updateEnterprisejButton.setVisible(false);
        saveEnterprisejButton.setVisible(true);
    }//GEN-LAST:event_newEnterprisejButtonActionPerformed

    private void departmentjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentjComboBoxActionPerformed
        Department dept = (Department)departmentjComboBox.getSelectedItem();
        if (dept != null){
            fillRolesComboBox(dept);
            fillEmployeeComboBox(dept);
        }
    }//GEN-LAST:event_departmentjComboBoxActionPerformed

    private void yearjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearjComboBoxActionPerformed
        calcDate();
    }//GEN-LAST:event_yearjComboBoxActionPerformed

    private void monthjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthjComboBoxActionPerformed
        calcDate();
    }//GEN-LAST:event_monthjComboBoxActionPerformed
    
    public void popDepartmentComboBox() {
        departmentjComboBox.removeAllItems();

        for (Department organization : enterprise.getDepartmentDirectory().getDepartmentList()) {
            departmentjComboBox.addItem(organization);
        }
    }
    
    public void fillEmployeeComboBox(Department organization){
        employeeComboBox.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            employeeComboBox.addItem(employee);
        }
    }
    
    private void fillRolesComboBox(Department organization){
        this.rolejComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            if (role.type.getValue().equals(role.type.MentalHealthWarrior.getValue()) || role.type.getValue().equals(role.type.WarriorRepresentative.getValue()) 
                    || role.type.getValue().equals(role.type.Donar.getValue()) || role.type.getValue().equals(role.type.CommunityEventsParticipants.getValue())){
                continue;
            }
            else{
                rolejComboBox.addItem(role);
            }
        }
    }

    
    public void displayDepartmentUsers() {

        DefaultTableModel model = (DefaultTableModel) enterprisessjTable.getModel();

        model.setRowCount(0);

        for (Department organization : enterprise.getDepartmentDirectory().getDepartmentList()) {
            
            for (Users ua : organization.getUsersDirectory().getUsersList()) {
                Object row[] = new Object[4];
                row[0] = ua;
                row[1] = ua.getRole();
                row[2] = ua.getEmployee();
                row[3] = ua.getNgoid();
                model.addRow(row);
            }
        }
    }
    
    static boolean checkMail(String email) {
      String mailregex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      return email.matches(mailregex);
    }
    
    private void calcDate(){
        int year=Integer.parseInt(yearjComboBox.getSelectedItem().toString());
        int month=Integer.parseInt(monthjComboBox.getSelectedItem().toString());
        LocalDate selDate=LocalDate.of(year, 01, 01);
        
        boolean leap=selDate.isLeapYear();
        days.removeAllElements();
        dayjComboBox.setModel(days);
//        dayjComboBox.removeAll();
        if(leap){
            if(month==2){
                for(int i=1;i<=29;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else if(month==4 || month==6 || month==9 || month==11){
                for(int i=1;i<=30;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else{
                for(int i=1;i<=31;i++){
                    days.addElement(String.valueOf(i));
                }
            }
        }
        else{
            if(month==2){
                for(int i=1;i<=28;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else if(month==4 || month==6 || month==9 || month==11){
                for(int i=1;i<=30;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else{
                for(int i=1;i<=31;i++){
                    days.addElement(String.valueOf(i));
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JComboBox<String> dayjComboBox;
    private javax.swing.JButton deleteEnterprisejButton;
    private javax.swing.JComboBox departmentjComboBox;
    private javax.swing.JTextField emailIdjTextField;
    private javax.swing.JComboBox employeeComboBox;
    private javax.swing.JLabel enterprisenamejLabel;
    private javax.swing.JTable enterprisessjTable;
    private javax.swing.JTextField firstnamejTextField;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnamejTextField;
    private javax.swing.JLabel loggedmhwjLabel;
    private javax.swing.JButton mhwLogoutjButton;
    private javax.swing.JComboBox<String> monthjComboBox;
    private javax.swing.JLabel networknamejLabel;
    private javax.swing.JButton newEnterprisejButton;
    private javax.swing.JPanel newUserjPanel;
    private javax.swing.JTextField ngoidjTextField;
    private javax.swing.JPasswordField passwordjPasswordField;
    private javax.swing.JTextField phonejTextField;
    private javax.swing.JComboBox rolejComboBox;
    private javax.swing.JButton saveEnterprisejButton;
    private javax.swing.JComboBox<String> sexjComboBox;
    private javax.swing.JTextField ssnnumberjTextField;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JButton updateEnterprisejButton;
    private javax.swing.JTextField usernamejTextField;
    private javax.swing.JComboBox<String> yearjComboBox;
    private javax.swing.JTextField zipcodejTextField;
    // End of variables declaration//GEN-END:variables
}
