/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.ProcessManagerRole;

import Controller.DB4OModel.DB4OModel;
import Controller.Department.Department;
import Controller.Department.OperationsDepartment;
import Controller.Enterprise.Enterprise;
import Controller.HealthNGO;
import Controller.Users.Users;
import Controller.WorkQueue.FundsRequestWorker;
import Controller.WorkQueue.ItemsRequestWorker;
import Controller.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class ProcessManagerWorkerjPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerjPanel
     */
    private HealthNGO system;
    private JPanel container,logincontainerJPanel;
    private Users user;
    private Enterprise enterprise;
    private Department org;
    private DB4OModel dB4OModel = DB4OModel.getInstance();
    public ProcessManagerWorkerjPanel(JPanel logincontainerJPanel,JPanel container,Enterprise enterprise,Department org, Users user, HealthNGO system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.enterprise=enterprise;
        this.user=user;
        this.loggedmhwjLabel.setText("Hi, "+user.getEmployee()+"("+user.getRole()+")");
        this.org=(OperationsDepartment)org;
        noneAssignedItemsRequests();
        itemsReqestsAssignedtoYou();
        displayFundsRequests();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loggedmhwjLabel = new javax.swing.JLabel();
        mhwLogoutjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        assignedItemsRequestsjTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        noneassignedItemsRequestsjTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        fundsRequestsjTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loggedmhwjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loggedmhwjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggedmhwjLabel.setText("Logged Username");
        loggedmhwjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mhwLogoutjButton.setBackground(new java.awt.Color(255, 255, 204));
        mhwLogoutjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mhwLogoutjButton.setText("Logout");
        mhwLogoutjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        mhwLogoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhwLogoutjButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setText("Support Ticket");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assigned Items Requests", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        assignedItemsRequestsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request", "Sender", "Message", "Qty", "Status", "Result"
            }
        ));
        assignedItemsRequestsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignedItemsRequestsjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(assignedItemsRequestsjTable);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "None Assigned Items Requests", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        noneassignedItemsRequestsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request", "Sender", "Message", "Status", "Result"
            }
        ));
        noneassignedItemsRequestsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noneassignedItemsRequestsjTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(noneassignedItemsRequestsjTable);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requested Funds", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        fundsRequestsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request", "Sender", "Receiver", "Message", "Amount", "Status", "Requested", "Result"
            }
        ));
        fundsRequestsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundsRequestsjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fundsRequestsjTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(831, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 381, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mhwLogoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhwLogoutjButtonActionPerformed
        JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;
    
        logincontainerJPanel.setVisible(true);
        container.removeAll();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Logged Out. Please Login to Continue");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        container.add(jPanel6);
    }//GEN-LAST:event_mhwLogoutjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        noneAssignedItemsRequests();
        itemsReqestsAssignedtoYou();
        displayFundsRequests();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void assignedItemsRequestsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignedItemsRequestsjTableMouseClicked
        int selectedRow = assignedItemsRequestsjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No Request Selected");
            return;
        }
        ItemsRequestWorker request = (ItemsRequestWorker)assignedItemsRequestsjTable.getValueAt(selectedRow, 0);
        
        ProcessManagerWorkerItemsReqestjPanel itemsProcess=new ProcessManagerWorkerItemsReqestjPanel(logincontainerJPanel,container,enterprise, user ,system,request);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("itemsProcess",itemsProcess);
        layout.next(container);
    }//GEN-LAST:event_assignedItemsRequestsjTableMouseClicked

    private void noneassignedItemsRequestsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noneassignedItemsRequestsjTableMouseClicked
        int selectedRow = noneassignedItemsRequestsjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No Item Request Selected");
            return;
        }
        String requests=noneassignedItemsRequestsjTable.getValueAt(selectedRow, 0).toString();
        if(requests.contains("Controller.WorkQueue.ItemsRequestWorker")){
            int confirm=JOptionPane.showConfirmDialog(null, "Assign Items Request To You?", "Assign Items Request Confirmation", JOptionPane.YES_NO_OPTION);
            if(confirm==0){
                ItemsRequestWorker itemRequest=(ItemsRequestWorker)noneassignedItemsRequestsjTable.getValueAt(selectedRow, 0);
                String rec=(itemRequest.getReceiver()!=null)?itemRequest.getReceiver().toString():"";
                if(rec.equals("")){
                    itemRequest.setReceiver(user);
                    itemRequest.setStatus("Received by Process Manager");
                }
                user.getWorkQueue().getWorkRequestList().add(itemRequest);
                dB4OModel.storeSystem(system);
                noneAssignedItemsRequests();
                itemsReqestsAssignedtoYou();
                JOptionPane.showMessageDialog(null, "This Request is now Assigned to You.");
            }
        }
    }//GEN-LAST:event_noneassignedItemsRequestsjTableMouseClicked

    private void fundsRequestsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundsRequestsjTableMouseClicked
        int selectedRow = fundsRequestsjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "No Request Selected");
            return;
        }
        String requests=fundsRequestsjTable.getValueAt(selectedRow, 0).toString();
        if(requests.contains("Controller.WorkQueue.FundsRequestWorker")){
            FundsRequestWorker funds=(FundsRequestWorker)fundsRequestsjTable.getValueAt(selectedRow, 0);
            ProcessManagerWorkerFundsRequestsjPanel fundsProcess=new ProcessManagerWorkerFundsRequestsjPanel(logincontainerJPanel,container,enterprise, user ,system,funds);
            CardLayout layout=(CardLayout)container.getLayout();
            container.add("fundsProcess",fundsProcess);
            layout.next(container);
        }

    }//GEN-LAST:event_fundsRequestsjTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ProcessManagerWorkerSupportTicketjPanel supportTicketProcess=new ProcessManagerWorkerSupportTicketjPanel(logincontainerJPanel,container,enterprise,org, user ,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("supportTicketProcess",supportTicketProcess);
        layout.next(container);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void noneAssignedItemsRequests(){
        DefaultTableModel model = (DefaultTableModel) noneassignedItemsRequestsjTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest order : org.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            String request=String.valueOf(order);
            if(request.contains("Controller.WorkQueue.ItemsRequestWorker")){
                String rec=(order.getReceiver()!=null)?order.getReceiver().toString():"";
                if(rec.equals("")){
                    row[0] = order;
                    row[1] = (order.getSender()!=null)?order.getSender():"";
                    row[2] = order.getMessage();
                    row[3] = order.getStatus();
                    String result = ((ItemsRequestWorker)order).getRequesteResult();
                    row[4] = result == null ? "Waiting" : result;
                    model.addRow(row);
                }
            }
        }
    }
    
    public void itemsReqestsAssignedtoYou(){
        DefaultTableModel model = (DefaultTableModel) assignedItemsRequestsjTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest order : user.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            String request=String.valueOf(order);
            if(request.contains("Controller.WorkQueue.ItemsRequestWorker")){
                String rec=(order.getReceiver()!=null)?order.getReceiver().toString():"";
                    row[0] = order;
                    row[1] = (order.getSender()!=null)?order.getSender():"";
                    row[2] = order.getMessage();
                    row[3] = ((ItemsRequestWorker)order).getQuantity();
                    row[4] = order.getStatus();
                    String result = ((ItemsRequestWorker)order).getRequesteResult();
                    row[5] = result == null ? "Waiting" : result;
                    model.addRow(row);
            }
        }
    }
    
    public void displayFundsRequests(){
        DefaultTableModel model = (DefaultTableModel) fundsRequestsjTable.getModel();
        model.setRowCount(0);
        for (WorkRequest order : org.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[8];
            String request=String.valueOf(order);
            if(request.contains("Controller.WorkQueue.FundsRequestWorker")){
                row[0] = order;
                row[1] = (order.getSender()!=null)?order.getSender():"";
                row[2] = (order.getReceiver()!=null)?order.getReceiver():"";
                row[3] = order.getMessage();
                row[4] = ((FundsRequestWorker)order).getAmount();
                row[5] = order.getStatus();
                row[6] = order.getRequestDate();
                String result = ((FundsRequestWorker)order).getRequesteResult();
                row[7] = result == null ? "Waiting" : result;
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assignedItemsRequestsjTable;
    private javax.swing.JTable fundsRequestsjTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel loggedmhwjLabel;
    private javax.swing.JButton mhwLogoutjButton;
    private javax.swing.JTable noneassignedItemsRequestsjTable;
    // End of variables declaration//GEN-END:variables
}
