/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.NGOVolunteer;

import Controller.DB4OModel.DB4OModel;
import Controller.Department.Department;
import Controller.Department.OperationsDepartment;
import Controller.Enterprise.Enterprise;
import Controller.HealthNGO;
import Controller.Medicine.Medicine;
import Controller.Network.Network;
import Controller.Users.Users;
import Controller.WorkQueue.FundsRequestWorker;
import Controller.WorkQueue.ItemsRequestWorker;
import Controller.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class NGOVolunteerWorkerjPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerjPanel
     */
    private HealthNGO system;
    private Enterprise enterprise;
    private Department org;
    private JPanel container,logincontainerJPanel;
    private Users user;
    private DB4OModel dB4OModel = DB4OModel.getInstance();
    public NGOVolunteerWorkerjPanel(JPanel logincontainerJPanel,JPanel container,Enterprise enterprise,Department org, Users user, HealthNGO system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.enterprise=enterprise;
        this.user=user;
        this.loggedmhwjLabel.setText("Hi, "+user.getEmployee()+"("+user.getRole()+")");
        fundsAmountjTextField.setText("");
        newFundsjButton.setVisible(false);
        deleteFundsjButton.setVisible(false);
        newItemRequestButton.setVisible(false);
        deleteItemsRequestjButton.setVisible(false);
        requestFundsjButton.setVisible(true);
        displayRequestedFunds();
        displayRequestedItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loggedmhwjLabel = new javax.swing.JLabel();
        mhwLogoutjButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestedFundsjTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fundsAmountjTextField = new javax.swing.JTextField();
        requestFundsjButton = new javax.swing.JButton();
        deleteFundsjButton = new javax.swing.JButton();
        newFundsjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fundsMessagejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemsMessagejTextField = new javax.swing.JTextField();
        itemsQuantityjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deleteItemsRequestjButton = new javax.swing.JButton();
        newItemRequestButton = new javax.swing.JButton();
        requestItemjButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestedItemsjTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loggedmhwjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loggedmhwjLabel.setText("Logged Username");
        loggedmhwjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mhwLogoutjButton.setBackground(new java.awt.Color(255, 255, 204));
        mhwLogoutjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mhwLogoutjButton.setText("Logout");
        mhwLogoutjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        mhwLogoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhwLogoutjButtonActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Refresh");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Support Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funds Requested", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        requestedFundsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Receiver", "Message", "Amount", "Status", "Result"
            }
        ));
        requestedFundsjTable.setGridColor(java.awt.SystemColor.window);
        requestedFundsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestedFundsjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(requestedFundsjTable);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fund or Items Request", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Amount");

        requestFundsjButton.setBackground(new java.awt.Color(204, 255, 204));
        requestFundsjButton.setText("Request Funds");
        requestFundsjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        requestFundsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestFundsjButtonActionPerformed(evt);
            }
        });

        deleteFundsjButton.setBackground(new java.awt.Color(204, 255, 204));
        deleteFundsjButton.setText("Delete");
        deleteFundsjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        deleteFundsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFundsjButtonActionPerformed(evt);
            }
        });

        newFundsjButton.setBackground(new java.awt.Color(204, 255, 204));
        newFundsjButton.setText("New");
        newFundsjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        newFundsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFundsjButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Funding Message");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Item Message");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Quantity");

        deleteItemsRequestjButton.setBackground(new java.awt.Color(204, 255, 204));
        deleteItemsRequestjButton.setText("Delete");
        deleteItemsRequestjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        deleteItemsRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemsRequestjButtonActionPerformed(evt);
            }
        });

        newItemRequestButton.setBackground(new java.awt.Color(204, 255, 204));
        newItemRequestButton.setText("New");
        newItemRequestButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        newItemRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newItemRequestButtonActionPerformed(evt);
            }
        });

        requestItemjButton.setBackground(new java.awt.Color(204, 255, 204));
        requestItemjButton.setText("Request Items");
        requestItemjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        requestItemjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestItemjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteFundsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newFundsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(requestFundsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fundsAmountjTextField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fundsMessagejTextField)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(requestItemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteItemsRequestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newItemRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemsQuantityjTextField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemsMessagejTextField)))
                        .addContainerGap())))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundsMessagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundsAmountjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteFundsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(requestFundsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newFundsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemsMessagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemsQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteItemsRequestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(requestItemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newItemRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(java.awt.SystemColor.window);
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items Requested", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        requestedItemsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Receiver", "Message", "Quantity", "Status", "Result"
            }
        ));
        requestedItemsjTable.setGridColor(java.awt.SystemColor.window);
        requestedItemsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestedItemsjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(requestedItemsjTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mhwLogoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhwLogoutjButtonActionPerformed
       JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;
    
        logincontainerJPanel.setVisible(true);
        container.removeAll();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Logged Out. Please Login to Continue");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        container.add(jPanel6);
    }//GEN-LAST:event_mhwLogoutjButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        displayRequestedFunds();
        displayRequestedItems();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void requestedFundsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestedFundsjTableMouseClicked
//       int selectedRow = requestedFundsjTable.getSelectedRow();
//        if (selectedRow < 0){
//            JOptionPane.showMessageDialog(null, "Select Medicine or Add.");
//            fundsAmountjTextField.setText("");
//            newFundsjButton.setVisible(false);
//            deleteFundsjButton.setVisible(false);
//            return;
//        }
//        Medicine medicine = (Medicine)requestedFundsjTable.getValueAt(selectedRow, 0);
//        fundsAmountjTextField.setText(String.valueOf(medicine.getQuantity()));
//        this.fundsMessagejTextField.setText(medicine.getName());
//        newFundsjButton.setVisible(true);
//        deleteFundsjButton.setVisible(true);
//        requestFundsjButton.setVisible(false);
    }//GEN-LAST:event_requestedFundsjTableMouseClicked

    private void requestFundsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestFundsjButtonActionPerformed
        String fundsMessage = fundsMessagejTextField.getText().trim();
        String fundsAmount =fundsAmountjTextField.getText().trim();
        double amount;
        if(fundsMessage.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Specify Fund Message Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(fundsMessage.length()<=3) {
            JOptionPane.showMessageDialog(this, "Fund Message must be Three characters and more", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(fundsMessage.length()>100) {
            JOptionPane.showMessageDialog(this, "Fund Message should have less than 100 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            amount=Double.parseDouble(fundsAmount);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Fund Amount Must be a Positive Integer Number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm=JOptionPane.showConfirmDialog(null, "Send Funds Request?", "Funds Request", JOptionPane.YES_NO_OPTION);
        if(confirm==0){
        FundsRequestWorker request = new FundsRequestWorker();
        request.setMessage(fundsMessage);
        request.setAmount(amount);
        request.setSender(user);
        request.setStatus("Funds Requested");
        Department operationsOrg=null;
        for(Network network:system.getNetworkList()){
                for(Enterprise enterprises:network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Department depart : enterprises.getDepartmentDirectory().getDepartmentList()){
                        if (depart instanceof OperationsDepartment){
                            operationsOrg = depart;
                            break;
                        }
                    }

                }
            }

            if(operationsOrg==null){
                JOptionPane.showMessageDialog(null, "Refund Request Not Sent");
                return;
            }
        operationsOrg.getWorkQueue().getWorkRequestList().add(request);
        user.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Funds Request Submitted.\nA Please Wait for responses.");
        dB4OModel.storeSystem(system);
        displayRequestedFunds();
        }
    }                                

    private void delUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {
             
    }//GEN-LAST:event_requestFundsjButtonActionPerformed

    private void deleteFundsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFundsjButtonActionPerformed
        int selectedRow = requestedFundsjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select Medicine or Add");
            fundsAmountjTextField.setText("");
            fundsMessagejTextField.setText("");
            newFundsjButton.setVisible(false);
            deleteFundsjButton.setVisible(false);
            return;
        }
        Medicine medicine = (Medicine)requestedFundsjTable.getValueAt(selectedRow, 0);
        system.getMedicinedirectory().getMedicineList().remove(medicine);
        dB4OModel.storeSystem(system);
        displayRequestedFunds();
        displayRequestedItems();
    }//GEN-LAST:event_deleteFundsjButtonActionPerformed

    private void newFundsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFundsjButtonActionPerformed
        this.fundsAmountjTextField.setText("");
        this.newFundsjButton.setVisible(false);
        deleteFundsjButton.setVisible(false);
        requestFundsjButton.setVisible(true);
    }//GEN-LAST:event_newFundsjButtonActionPerformed

    private void requestedItemsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestedItemsjTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_requestedItemsjTableMouseClicked

    private void deleteItemsRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemsRequestjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteItemsRequestjButtonActionPerformed

    private void newItemRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newItemRequestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newItemRequestButtonActionPerformed

    private void requestItemjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestItemjButtonActionPerformed
        String fundsMessage = itemsMessagejTextField.getText().trim();
        String fundsAmount =itemsQuantityjTextField.getText().trim();
        double quantity;
        if(fundsMessage.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Specify Items Message Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(fundsMessage.length()<=3) {
            JOptionPane.showMessageDialog(this, "Items must be Three characters and more", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(fundsMessage.length()>100) {
            JOptionPane.showMessageDialog(this, "Items Message should have less than 100 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            quantity=Double.parseDouble(fundsAmount);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Items Quantity Must be a Positive Integer Number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm=JOptionPane.showConfirmDialog(null, "Send Items Request?", "Items Request", JOptionPane.YES_NO_OPTION);
        if(confirm==0){
        ItemsRequestWorker request = new ItemsRequestWorker();
        request.setMessage(fundsMessage);
        request.setQuantity(quantity);
        request.setSender(user);
        request.setStatus("Items Requested");
        Department operationsOrg=null;
        for(Network network:system.getNetworkList()){
                for(Enterprise enterprises:network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Department depart : enterprises.getDepartmentDirectory().getDepartmentList()){
                        if (depart instanceof OperationsDepartment){
                            operationsOrg = depart;
                            break;
                        }
                    }

                }
            }

            if(operationsOrg==null){
                JOptionPane.showMessageDialog(null, "Items Request Not Sent");
                return;
            }
        operationsOrg.getWorkQueue().getWorkRequestList().add(request);
        user.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Items Request Submitted.\nA Please Wait for responses.");
        dB4OModel.storeSystem(system);
        displayRequestedFunds();
        displayRequestedItems();
        }
    }//GEN-LAST:event_requestItemjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NGOVolunteerWorkerSupportTicketjPanel ngoVolunteersupportTicketProcess=new NGOVolunteerWorkerSupportTicketjPanel(logincontainerJPanel,container,enterprise,org, user ,system);
        CardLayout layout=(CardLayout)container.getLayout();
        container.add("ngoVolunteersupportTicketProcess",ngoVolunteersupportTicketProcess);
        layout.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed
     
    public void displayRequestedFunds(){
        DefaultTableModel model = (DefaultTableModel) requestedFundsjTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest order : user.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            String request=String.valueOf(order);
            if(request.contains("Controller.WorkQueue.FundsRequestWorker")){
                row[0] = order;
                row[1] = (order.getReceiver()!=null)?order.getReceiver():"";
                row[2] = order.getMessage();
                row[3] = ((FundsRequestWorker)order).getAmount();
                row[4] = order.getStatus();
                String result = ((FundsRequestWorker)order).getRequesteResult();
                row[5] = result == null ? "Waiting" : result;
                model.addRow(row);
            }
        }
    }
    
    public void displayRequestedItems(){
        DefaultTableModel model = (DefaultTableModel) requestedItemsjTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest order : user.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            String request=String.valueOf(order);
            if(request.contains("Controller.WorkQueue.ItemsRequestWorker")){
                row[0] = order;
                row[1] = (order.getReceiver()!=null)?order.getReceiver():"";
                row[2] = order.getMessage();
                row[3] = ((ItemsRequestWorker)order).getQuantity();
                row[4] = order.getStatus();
                String result = ((ItemsRequestWorker)order).getRequesteResult();
                row[5] = result == null ? "Waiting" : result;
                model.addRow(row);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteFundsjButton;
    private javax.swing.JButton deleteItemsRequestjButton;
    private javax.swing.JTextField fundsAmountjTextField;
    private javax.swing.JTextField fundsMessagejTextField;
    private javax.swing.JTextField itemsMessagejTextField;
    private javax.swing.JTextField itemsQuantityjTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loggedmhwjLabel;
    private javax.swing.JButton mhwLogoutjButton;
    private javax.swing.JButton newFundsjButton;
    private javax.swing.JButton newItemRequestButton;
    private javax.swing.JButton requestFundsjButton;
    private javax.swing.JButton requestItemjButton;
    private javax.swing.JTable requestedFundsjTable;
    private javax.swing.JTable requestedItemsjTable;
    // End of variables declaration//GEN-END:variables
}
