/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Sysadmin;

import Controller.DB4OModel.DB4OModel;
import Controller.Department.Department;
import Controller.Enterprise.Enterprise;
import Controller.HealthNGO;
import Controller.Network.Network;
import Controller.Role.AdministrationAssistanceRole;
import Controller.Role.BillingAgentRole;
import Controller.Role.CommunityEventsParticipantsRole;
import Controller.Role.CommunityManagerRole;
import Controller.Role.CriticalCareManagerRole;
import Controller.Role.DonationsManagerRole;
import Controller.Role.DonorRole;
import Controller.Role.DrugDeliveryAgentRole;
import Controller.Role.EmergencyMedicineDoctorRole;
import Controller.Role.EmergencyVehicleDriverRole;
import Controller.Role.FinanceManagerRole;
import Controller.Role.HelpDeskAgentRole;
import Controller.Role.ITAdminRole;
import Controller.Role.LifelineAgentRole;
import Controller.Role.MentalHealthWarriorRole;
import Controller.Role.NGOVolunteerRole;
import Controller.Role.NLPTrainerRole;
import Controller.Role.NurseRole;
import Controller.Role.PharmacistRole;
import Controller.Role.PharmacyBillingAgentRole;
import Controller.Role.ProcessManagerRole;
import Controller.Role.PsychiatristRole;
import Controller.Role.RehabDoctorRole;
import Controller.Role.SupplyChainManagerRole;
import Controller.Role.SystemAdminRole;
import Controller.Role.TreasurerRole;
import Controller.Role.WarriorRepresentativeRole;
import Controller.Role.WebsiteManagerRole;
import Controller.Users.Users;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class SysAdminWorkerLoginUserReportsjPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerjPanel
     */
    private HealthNGO system;
    private JPanel container,logincontainerJPanel,sysadminLoginjPanel,stardardLoginjPanel;
    private Users user;
    private DB4OModel dB4OModel = DB4OModel.getInstance();
    private String thisnetworkname;
    public SysAdminWorkerLoginUserReportsjPanel(JPanel sysadminLoginjPanel,JPanel stardardLoginjPanel,JPanel logincontainerJPanel,JPanel container, Users user, HealthNGO system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.user=user;
        this.loggedmhwjLabel.setText("Hi, "+user.getEmployee());
        this.sysadminLoginjPanel=sysadminLoginjPanel;
        this.stardardLoginjPanel=stardardLoginjPanel;
        String networkname="";
        for(Network network:system.getNetworkList()){
            networkname=network.getName();
        }
        this.thisnetworkname=networkname;
        this.networknamejLabel.setText(networkname);
        DisplayEnterpisesAdmins();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loggedmhwjLabel = new javax.swing.JLabel();
        mhwLogoutjButton = new javax.swing.JButton();
        networknamejLabel = new javax.swing.JLabel();
        sysQuitjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        loginUsersjPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loggedmhwjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loggedmhwjLabel.setText("Logged Username");
        loggedmhwjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mhwLogoutjButton.setBackground(new java.awt.Color(255, 255, 204));
        mhwLogoutjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mhwLogoutjButton.setText("Logout");
        mhwLogoutjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        mhwLogoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhwLogoutjButtonActionPerformed(evt);
            }
        });

        networknamejLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        networknamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        networknamejLabel.setText("Logged Network");
        networknamejLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        sysQuitjButton.setBackground(java.awt.SystemColor.window);
        sysQuitjButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        sysQuitjButton.setForeground(java.awt.Color.red);
        sysQuitjButton.setText("Lock");
        sysQuitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysQuitjButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("<< Back");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(networknamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysQuitjButton)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(networknamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(sysQuitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        loginUsersjPanel.setBackground(new java.awt.Color(0, 153, 153));
        loginUsersjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Login Users", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        javax.swing.GroupLayout loginUsersjPanelLayout = new javax.swing.GroupLayout(loginUsersjPanel);
        loginUsersjPanel.setLayout(loginUsersjPanelLayout);
        loginUsersjPanelLayout.setHorizontalGroup(
            loginUsersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        loginUsersjPanelLayout.setVerticalGroup(
            loginUsersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginUsersjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsersjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mhwLogoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhwLogoutjButtonActionPerformed
        JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;
    
        logincontainerJPanel.setVisible(true);
        sysadminLoginjPanel.setVisible(false);
        stardardLoginjPanel.setVisible(true);
        container.removeAll();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Logged Out. Please Login to Continue");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        container.add(jPanel6);
    }//GEN-LAST:event_mhwLogoutjButtonActionPerformed

    private void sysQuitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysQuitjButtonActionPerformed
        JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;
    
        logincontainerJPanel.setVisible(true);
        sysadminLoginjPanel.setVisible(true);
        stardardLoginjPanel.setVisible(false);
        container.removeAll();
        
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Locked. Please Login to Authorize");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        
        container.add(jPanel6);
        
    }//GEN-LAST:event_sysQuitjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DisplayEnterpisesAdmins() {
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        int ITAdmin=0;
        int WebsiteManager=0;
        int CommunityManager=0;
        int HelpDeskAgent=0;
        int ProcessManager=0;
        int DonationManager=0;
        int Treasurer=0;
        int FinanceManager=0;
        int Psychiastrist=0;
        int BillingAgent=0;
        int Nurse=0;
        int EmergencyVehicleDri=0;
        int EmergencyMedicineDoc=0;
        int CriticalCareManager=0;
        int Pharmacist=0;
        int DrugDeliveryAgent=0;
        int PharmacyBillingAgent=0;
        int SupplyChainManager=0;
        int Donar=0;
        int NGOVolunteer=0;
        int CommunityEventsParticipants=0;
        int LifelineAgent=0;
        int AdministrationAssistance=0;
        int NLPTrainer=0;
        int MentalHealthWarrior=0;
        int RehabDoctor=0;
        int WarriorRepresentative=0;
        int SysAdmin=0;
        for (Users users : system.getUsersDirectory().getUsersList()) {
//            System.out.println("System "+users+" "+users.getRole());
            if(users.getRole() instanceof SystemAdminRole){
                SysAdmin++;
            }
            else if(users.getRole() instanceof DonorRole){
                Donar++;
            }
            else if(users.getRole() instanceof CommunityEventsParticipantsRole){
                CommunityEventsParticipants++;
            }
            else if(users.getRole() instanceof MentalHealthWarriorRole){
                MentalHealthWarrior++;
            }
            else if(users.getRole() instanceof WarriorRepresentativeRole){
                WarriorRepresentative++;
            }
        }
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for(Users users:enterprise.getUsersDirectory().getUsersList()){
                    if(users.getRole() instanceof AdministrationAssistanceRole){
                        AdministrationAssistance++;
                    }
                }
                for(Department organizations:enterprise.getDepartmentDirectory().getDepartmentList()){
                    for(Users users:organizations.getUsersDirectory().getUsersList()){
//                        System.out.println(enterprise+" "+users+" "+users.getRole());
                        if(users.getRole() instanceof HelpDeskAgentRole){
                            HelpDeskAgent++;
                        }
                        else if(users.getRole() instanceof FinanceManagerRole){
                            FinanceManager++;
                        }
                        else if(users.getRole() instanceof TreasurerRole){
                            Treasurer++;
                        }
                        else if(users.getRole() instanceof DonationsManagerRole){
                            DonationManager++;
                        }
                        else if(users.getRole() instanceof ITAdminRole){
                            ITAdmin++;
                        }
                        else if(users.getRole() instanceof WebsiteManagerRole){
                            WebsiteManager++;
                        }
                        else if(users.getRole() instanceof ProcessManagerRole){
                            ProcessManager++;
                        }
                        else if(users.getRole() instanceof CommunityManagerRole){
                            CommunityManager++;
                        }
                        else if(users.getRole() instanceof PsychiatristRole){
                            Psychiastrist++;
                        }
                        else if(users.getRole() instanceof BillingAgentRole){
                            BillingAgent++;
                        }
                        else if(users.getRole() instanceof NurseRole){
                            Nurse++;
                        }
                        else if(users.getRole() instanceof EmergencyVehicleDriverRole){
                            EmergencyVehicleDri++;
                        }
                        else if(users.getRole() instanceof EmergencyMedicineDoctorRole){
                            EmergencyMedicineDoc++;
                        }
                        else if(users.getRole() instanceof CriticalCareManagerRole){
                            CriticalCareManager++;
                        }
                        else if(users.getRole() instanceof SupplyChainManagerRole){
                            SupplyChainManager++;
                        }
                        else if(users.getRole() instanceof PharmacistRole){
                            Pharmacist++;
                        }
                        else if(users.getRole() instanceof DrugDeliveryAgentRole){
                            DrugDeliveryAgent++;
                        }
                        else if(users.getRole() instanceof LifelineAgentRole){
                            LifelineAgent++;
                        }
                        else if(users.getRole() instanceof NLPTrainerRole){
                            NLPTrainer++;
                        }
                        else if(users.getRole() instanceof RehabDoctorRole){
                            RehabDoctor++;
                        }
                        else if(users.getRole() instanceof NGOVolunteerRole){
                            NGOVolunteer++;
                        }
                        else if(users.getRole() instanceof ProcessManagerRole){
                            ProcessManager++;
                        }
                        else if(users.getRole() instanceof PharmacyBillingAgentRole){
                            PharmacyBillingAgent++;
                        }
                    }
                }
            }
        }
        dataset.addValue(SysAdmin ,"Sysadmin", "No Of Users");
        dataset.addValue(AdministrationAssistance ,"Admin", "No Of Users");
        dataset.addValue(HelpDeskAgent ,"HDA", "No Of Users");
        dataset.addValue(FinanceManager ,"Finance Manager", "No Of Users");
        dataset.addValue(Treasurer ,"Treasurer", "No Of Users");
        dataset.addValue(DonationManager ,"Donation Manager", "No Of Users");
        dataset.addValue(ITAdmin ,"IT Admin", "No Of Users");
        dataset.addValue(WebsiteManager ,"Website Manager", "No Of Users");
        dataset.addValue(ProcessManager ,"Process Manager", "No Of Users");
        dataset.addValue(CommunityManager ,"Community Manager", "No Of Users");
        dataset.addValue(Psychiastrist ,"Psychiatrist", "No Of Users");
        dataset.addValue(BillingAgent ,"Hospital Billing Agent", "No Of Users");
        dataset.addValue(Nurse ,"Nurse", "No Of Users");
        dataset.addValue(EmergencyMedicineDoc ,"Emergency Medicine Doctor", "No Of Users");
        dataset.addValue(EmergencyVehicleDri ,"Emergency Vehicle Driver", "No Of Users");
        dataset.addValue(CriticalCareManager ,"Critical Care Manager", "No Of Users");
        dataset.addValue(SupplyChainManager ,"Supply Chain Manager", "No Of Users");
        dataset.addValue(Pharmacist ,"Pharmacist", "No Of Users");
        dataset.addValue(DrugDeliveryAgent ,"Drug Delivery Agent", "No Of Users");
        dataset.addValue(PharmacyBillingAgent ,"Pharmacy Billing Agent", "No Of Users");
        dataset.addValue(LifelineAgent ,"Lifeline Agent", "No Of Users");
        dataset.addValue(NLPTrainer ,"NLP Trainer", "No Of Users");
        dataset.addValue(RehabDoctor ,"RehabDoctor", "No Of Users");
        dataset.addValue(NGOVolunteer ,"NGO Volunteer", "No Of Users");
        dataset.addValue(Donar ,"Donar", "No Of Users");
        dataset.addValue(CommunityEventsParticipants ,"Community Events Participants", "No Of Users");
        dataset.addValue(MentalHealthWarrior ,"Mental Health Warrior", "No Of Users");
        dataset.addValue(WarriorRepresentative ,"Warrior Representative", "No Of Users");
        JFreeChart chart=ChartFactory.createBarChart3D(this.thisnetworkname, "Login User Roles", "Number of Users", dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot plot=chart.getCategoryPlot();
        
        plot.setRangeGridlinePaint(Color.gray);
        plot.setBackgroundPaint(Color.WHITE);
        plot.setDomainCrosshairPaint(Color.BLUE);
        
        BarRenderer render=(BarRenderer)plot.getRenderer();
        render.setSeriesPaint(0, Color.BLUE);
        ChartPanel chartPanel=new ChartPanel(chart);
        chartPanel.setAutoscrolls(true);
        
        loginUsersjPanel.setLayout(new java.awt.BorderLayout());
       
        loginUsersjPanel.removeAll();
        loginUsersjPanel.add(chartPanel,BorderLayout.CENTER);
        loginUsersjPanel.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loggedmhwjLabel;
    private javax.swing.JPanel loginUsersjPanel;
    private javax.swing.JButton mhwLogoutjButton;
    private javax.swing.JLabel networknamejLabel;
    private javax.swing.JButton sysQuitjButton;
    // End of variables declaration//GEN-END:variables
}
