/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.CommunityManagerRole;

import Controller.DB4OModel.DB4OModel;
import Controller.Department.Department;
import Controller.Enterprise.Enterprise;
import Controller.Events.Events;
import Controller.Events.EventsParticipant;
import Controller.HealthNGO;
import Controller.Users.Users;
import java.awt.CardLayout;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saamu
 */
@SuppressWarnings("unchecked")
public class CommunityEventsManageWorkerjPanel extends javax.swing.JPanel {

    /**
     * Creates new form MentalHealthWorkerjPanel
     */
    private HealthNGO system;
    private Enterprise enterprise;
    private Department org;
    private JPanel container,logincontainerJPanel;
    private Users user;
    private DB4OModel dB4OModel = DB4OModel.getInstance();
    private DefaultComboBoxModel days=new DefaultComboBoxModel();
    public CommunityEventsManageWorkerjPanel(JPanel logincontainerJPanel,JPanel container,Enterprise enterprise,Department org, Users user, HealthNGO system) {
        initComponents();
        this.system=system;
        this.container=container;
        this.logincontainerJPanel=logincontainerJPanel;
        this.enterprise=enterprise;
        this.user=user;
        this.loggedmhwjLabel.setText("Hi, "+user.getEmployee()+"("+user.getRole()+")");
        enterprisenamejLabel.setText(enterprise.getName());
        eventDescjTextField.setText("");
        newMedicineButton.setVisible(false);
        updateNameButton.setVisible(false);
        deleteMedicinejButton.setVisible(false);
        saveEnterprisejButton.setVisible(true);
        
        yearjComboBox.removeAll();
        LocalDate nowDate=LocalDate.now();
        int year=nowDate.getYear();
        int startYear=1940;
        for(int i=year;i>=startYear;i--){
            yearjComboBox.addItem(String.valueOf(i));
        }
        displayEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loggedmhwjLabel = new javax.swing.JLabel();
        mhwLogoutjButton = new javax.swing.JButton();
        enterprisenamejLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisessjTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eventDescjTextField = new javax.swing.JTextField();
        saveEnterprisejButton = new javax.swing.JButton();
        updateNameButton = new javax.swing.JButton();
        deleteMedicinejButton = new javax.swing.JButton();
        newMedicineButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        eventNamejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eventVenuejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yearjComboBox = new javax.swing.JComboBox<>();
        monthjComboBox = new javax.swing.JComboBox<>();
        dayjComboBox = new javax.swing.JComboBox<>();
        minsjComboBox = new javax.swing.JComboBox<>();
        hoursjComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        donarDonationsjTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(java.awt.SystemColor.window);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loggedmhwjLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loggedmhwjLabel.setText("Logged Username");
        loggedmhwjLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mhwLogoutjButton.setBackground(new java.awt.Color(255, 255, 204));
        mhwLogoutjButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mhwLogoutjButton.setText("Logout");
        mhwLogoutjButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        mhwLogoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhwLogoutjButtonActionPerformed(evt);
            }
        });

        enterprisenamejLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enterprisenamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterprisenamejLabel.setText("Enterprise");
        enterprisenamejLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Refresh");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("<< Back");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterprisenamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loggedmhwjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mhwLogoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enterprisenamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Events Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        enterprisessjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Description", "Venue", "DateTime", "Status"
            }
        ));
        enterprisessjTable.setGridColor(java.awt.SystemColor.window);
        enterprisessjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterprisessjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterprisessjTable);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Event Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Description");

        saveEnterprisejButton.setBackground(new java.awt.Color(204, 255, 204));
        saveEnterprisejButton.setText("Save New");
        saveEnterprisejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        saveEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEnterprisejButtonActionPerformed(evt);
            }
        });

        updateNameButton.setBackground(new java.awt.Color(204, 255, 204));
        updateNameButton.setText("Update");
        updateNameButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        updateNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNameButtonActionPerformed(evt);
            }
        });

        deleteMedicinejButton.setBackground(new java.awt.Color(204, 255, 204));
        deleteMedicinejButton.setText("Delete");
        deleteMedicinejButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        deleteMedicinejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMedicinejButtonActionPerformed(evt);
            }
        });

        newMedicineButton.setBackground(new java.awt.Color(204, 255, 204));
        newMedicineButton.setText("New");
        newMedicineButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        newMedicineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMedicineButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Event Name");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Venue");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Date");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Time");

        yearjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearjComboBoxActionPerformed(evt);
            }
        });

        monthjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthjComboBoxActionPerformed(evt);
            }
        });

        minsjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "56", "57", "58", "59" }));

        hoursjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Event Participants"));

        donarDonationsjTextArea.setEditable(false);
        donarDonationsjTextArea.setColumns(20);
        donarDonationsjTextArea.setRows(5);
        jScrollPane2.setViewportView(donarDonationsjTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 60, Short.MAX_VALUE)
                                .addComponent(updateNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteMedicinejButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newMedicineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(saveEnterprisejButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eventDescjTextField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eventNamejTextField)))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventVenuejTextField)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(monthjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dayjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoursjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(minsjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(89, 89, 89)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventDescjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventVenuejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(yearjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(monthjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dayjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minsjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newMedicineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteMedicinejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 287, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mhwLogoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhwLogoutjButtonActionPerformed
       JLabel jLabel3;
        JLabel jLabel1;
        JPanel jPanel6;
    
        logincontainerJPanel.setVisible(true);
        container.removeAll();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jLabel1.setText("You have been Logged Out. Please Login to Continue");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/withYouNGO - Copy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(896, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        container.add(jPanel6);
    }//GEN-LAST:event_mhwLogoutjButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        displayEvents();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void enterprisessjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterprisessjTableMouseClicked
       int selectedRow = enterprisessjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select Event or Add.");
            eventDescjTextField.setText("");
            eventNamejTextField.setText("");
            eventVenuejTextField.setText("");
            newMedicineButton.setVisible(false);
            updateNameButton.setVisible(false);
            deleteMedicinejButton.setVisible(false);
            return;
        }
        Events event = (Events)enterprisessjTable.getValueAt(selectedRow, 0);
        eventDescjTextField.setText(event.getDescription());
        eventNamejTextField.setText(event.getName());
        eventVenuejTextField.setText(event.getVenue());
        
        String eventParticipatedStr="";
        int sno=1;
        for (EventsParticipant eventParticipated : system.getEventParticipantDirectory().getEventsParticipantList()){
            String rec=(eventParticipated.getEvent()!=null)?eventParticipated.getEvent().toString():"";
            if(rec.equals("") || (eventParticipated.getEvent()==event)){
                eventParticipatedStr+=eventParticipatedStr+sno+". "+eventParticipated.getParticipant().toFullname()+" "+eventParticipated.getRegisteredOn()+"\n\n";
                sno++;
            }
        }
        donarDonationsjTextArea.setText(eventParticipatedStr);
        
    }//GEN-LAST:event_enterprisessjTableMouseClicked

    private void saveEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEnterprisejButtonActionPerformed
        String eventname = eventNamejTextField.getText().trim();
        String eventdesc =eventDescjTextField.getText().trim();
        String eventvenue =eventVenuejTextField.getText().trim();
        int year=Integer.parseInt(yearjComboBox.getSelectedItem().toString());
        int month=Integer.parseInt(monthjComboBox.getSelectedItem().toString());
        int day=Integer.parseInt(monthjComboBox.getSelectedItem().toString());
        String hours=hoursjComboBox.getSelectedItem().toString();
        String mins=minsjComboBox.getSelectedItem().toString();
        LocalDate selDate;
        String eventdate,eventtime;
        eventtime=hours+":"+mins;
        if(eventname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Specify Event Name", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(eventname.length()<=3) {
            JOptionPane.showMessageDialog(this, "Event Name must be Three characters and more", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(eventname.length()>100) {
            JOptionPane.showMessageDialog(this, "Event Name should have less than 100 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(eventdesc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Specify Event Description", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(eventdesc.length()<=3) {
            JOptionPane.showMessageDialog(this, "Event Description must be Three characters and more", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(eventdesc.length()>100) {
            JOptionPane.showMessageDialog(this, "Event Description should have less than 100 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(eventvenue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Specify Event Venue", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(eventvenue.length()<=3) {
            JOptionPane.showMessageDialog(this, "Event Venue must be Three characters and more", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(eventvenue.length()>100) {
            JOptionPane.showMessageDialog(this, "Event Venue should have less than 100 characters", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            selDate=LocalDate.of(year, month, day);
            eventdate=selDate.toString();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Invalid Date.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!system.getEventDirectory().checkIfEventIsUnique(eventname)){
            JOptionPane.showMessageDialog(this, "Event Name Exists", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        system.getEventDirectory().createEvent(eventname, eventdesc, eventvenue, eventdate, eventtime, "Active");
        dB4OModel.storeSystem(system);
        displayEvents();
    }                                

    private void delUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {
             
    }//GEN-LAST:event_saveEnterprisejButtonActionPerformed

    private void updateNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNameButtonActionPerformed
        int selectedRow = enterprisessjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select event or Add.");
            eventNamejTextField.setText("");
            eventDescjTextField.setText("");
            newMedicineButton.setVisible(false);
            updateNameButton.setVisible(false);
            deleteMedicinejButton.setVisible(false);
            return;
        }
        
//        String medicinename = eventNamejTextField.getText().trim();
//        if(medicinename.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Specify Medicine Name", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        if(medicinename.length()<=3) {
//            JOptionPane.showMessageDialog(this, "Medicine Name must be Three characters and more", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        if(medicinename.length()>100) {
//            JOptionPane.showMessageDialog(this, "Medicine Name should have less than 100 characters", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        
//        if(!system.getMedicinedirectory().checkIfMedicineIsUnique(medicinename)){
//            JOptionPane.showMessageDialog(this, "Medicine Name Exists", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        
//        Medicine medicine = (Medicine)enterprisessjTable.getValueAt(selectedRow, 0);
//        medicine.setName(medicinename);
        
        dB4OModel.storeSystem(system);
        displayEvents();
    }//GEN-LAST:event_updateNameButtonActionPerformed

    private void deleteMedicinejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMedicinejButtonActionPerformed
        int selectedRow = enterprisessjTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select Event or Add");
            eventDescjTextField.setText("");
            eventNamejTextField.setText("");
            newMedicineButton.setVisible(false);
            updateNameButton.setVisible(false);
            deleteMedicinejButton.setVisible(false);
            return;
        }
//        Medicine medicine = (Medicine)enterprisessjTable.getValueAt(selectedRow, 0);
//        system.getMedicinedirectory().getMedicineList().remove(medicine);
        dB4OModel.storeSystem(system);
        displayEvents();
    }//GEN-LAST:event_deleteMedicinejButtonActionPerformed

    private void newMedicineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMedicineButtonActionPerformed
        this.eventDescjTextField.setText("");
        this.newMedicineButton.setVisible(false);
        updateNameButton.setVisible(false);
        deleteMedicinejButton.setVisible(false);
        saveEnterprisejButton.setVisible(true);
    }//GEN-LAST:event_newMedicineButtonActionPerformed

    private void yearjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearjComboBoxActionPerformed
        calcDate();
    }//GEN-LAST:event_yearjComboBoxActionPerformed

    private void monthjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthjComboBoxActionPerformed
        calcDate();
    }//GEN-LAST:event_monthjComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed
     
    private void displayEvents(){
        DefaultTableModel model = (DefaultTableModel) enterprisessjTable.getModel();
        
        model.setRowCount(0);
        for (Events event : system.getEventDirectory().getEventsList()){
            Object[] row = new Object[5];
            row[0] = event;
            row[1] = event.getDescription();
            row[2] = event.getVenue();
            row[3] = event.getDate()+" "+event.getTime();
            row[4] = event.getStatus();
            model.addRow(row);
        }
    }
    
    private void calcDate(){
        int year=Integer.parseInt(yearjComboBox.getSelectedItem().toString());
        int month=Integer.parseInt(monthjComboBox.getSelectedItem().toString());
        LocalDate selDate=LocalDate.of(year, 01, 01);
        
        boolean leap=selDate.isLeapYear();
        days.removeAllElements();
        dayjComboBox.setModel(days);
//        dayjComboBox.removeAll();
        if(leap){
            if(month==2){
                for(int i=1;i<=29;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else if(month==4 || month==6 || month==9 || month==11){
                for(int i=1;i<=30;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else{
                for(int i=1;i<=31;i++){
                    days.addElement(String.valueOf(i));
                }
            }
        }
        else{
            if(month==2){
                for(int i=1;i<=28;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else if(month==4 || month==6 || month==9 || month==11){
                for(int i=1;i<=30;i++){
                    days.addElement(String.valueOf(i));
                }
            }
            else{
                for(int i=1;i<=31;i++){
                    days.addElement(String.valueOf(i));
                }
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dayjComboBox;
    private javax.swing.JButton deleteMedicinejButton;
    private javax.swing.JTextArea donarDonationsjTextArea;
    private javax.swing.JLabel enterprisenamejLabel;
    private javax.swing.JTable enterprisessjTable;
    private javax.swing.JTextField eventDescjTextField;
    private javax.swing.JTextField eventNamejTextField;
    private javax.swing.JTextField eventVenuejTextField;
    private javax.swing.JComboBox<String> hoursjComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loggedmhwjLabel;
    private javax.swing.JButton mhwLogoutjButton;
    private javax.swing.JComboBox<String> minsjComboBox;
    private javax.swing.JComboBox<String> monthjComboBox;
    private javax.swing.JButton newMedicineButton;
    private javax.swing.JButton saveEnterprisejButton;
    private javax.swing.JButton updateNameButton;
    private javax.swing.JComboBox<String> yearjComboBox;
    // End of variables declaration//GEN-END:variables
}
